FROM openjdk:17-jdk

VOLUME /tmp
WORKDIR /app/log
WORKDIR /app/security/key

COPY target/*.jar /app/app.jar

ENV CONFIG_SERVER_HOST=${CONFIG_SERVER_HOST}

ENV DATASOURCE_URL=${DATASOURCE_URL}
ENV DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
ENV DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
ENV DATASOURCE_SCHEME=${DATASOURCE_SCHEME}

ENV JWT_PRIVATE_KEY=/app/security/key/app.key
ENV JWT_PUBLIC_KEY=/app/security/key/app.pub

ENV REDIS_HOST=${REDIS_HOST}
ENV REDIS_PASSWORD=${REDIS_PASSWORD}
ENV REDIS_PORT=${REDIS_PORT}

ENV LOG_DIR=/app/log

ENTRYPOINT ["java", "-jar", "/app/app.jar"]