FROM openjdk:17-jdk

VOLUME /tmp
WORKDIR /app/log
WORKDIR /app/security/key

COPY target/*.jar /app/app.jar

ARG CONFIG_SERVER_HOST
ARG DATASOURCE_URL
ARG DATASOURCE_USERNAME
ARG DATASOURCE_PASSWORD
ARG REDIS_HOST
ARG REDIS_PORT

ENV CONFIG_SERVER_HOST=${CONFIG_SERVER_HOST}

ENV DATASOURCE_URL=${DATASOURCE_URL}
ENV DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
ENV DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
ENV DATASOURCE_SCHEME=user_ms

ENV JWT_PRIVATE_KEY=file:/app/security/key/app.key
ENV JWT_PUBLIC_KEY=file:/app/security/key/app.pub

ENV REDIS_HOST=${REDIS_HOST}
ENV REDIS_PASSWORD=${REDIS_PASSWORD}
ENV REDIS_PORT=${REDIS_PORT}

ENV LOG_DIR=/app/log

ENV JAVA_OPTS="-Xms512m -Xmx1024m -XX:+UseG1GC"

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar /app/app.jar"]