spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user
    username: auth-ms
    password: auth-ms
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update