spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/kaliware
    username: user_service
    password: user_service
    hikari:
      schema: user
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
